### ISSUE TITLE
Implement AsRawFd for &mut Pty

### ISSUE THREAD

**Issue by crumblingstatue** [doy/pty-process#4]
```Rust
impl std::os::unix::io::AsRawFd for &mut Pty {
    fn as_raw_fd(&self) -> std::os::unix::io::RawFd {
        (**self).as_raw_fd()
    }
}
```

This allows usage with a [`NonBlockingReader`](https://docs.rs/nonblock/0.1.0/nonblock/struct.NonBlockingReader.html#method.from_fd) from the nonblock crate.

An alternative would be native non-blocking support. I want to use simple nonblocking reads without async.

**Comment by doy** [comment]
done in 1e4f4258fadabf349755c41bfb568d4331f8e2a0
